# -*- coding: utf-8 -*-
"""Kelas_dan_Objek_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1blhw_5C0Isbtef8MlsB_WO30dcIkh7Po

# Kelas dan Objek Python

## Pendahuluan
Python adalah bahasa pemrograman berorientasi objek. Hampir semua hal di Python adalah objek, dengan properti dan metodenya.
Kelas adalah seperti cetak biru untuk membuat objek.

## Membuat Kelas
"""

# Contoh: Membuat kelas bernama MyClass dengan properti x
class MyClass:
    x = 5

"""## Membuat Objek"""

# Contoh: Membuat objek dari kelas MyClass dan mencetak nilai x
p1 = MyClass()
print(p1.x)

p2 = MyClass()
print(p2.x * 2)

"""## Fungsi __init__()"""

# Contoh: Menggunakan __init__() untuk menetapkan properti
class Person:
    def __init__(self, name, age): # Fungsi ini berisi karakteristik dari si Class / Blueprint
        self.name = name
        self.age = age

p1 = Person("John", 36) # Object pertama
print(p1.name)
print(p1.age)

p2 = Person("Arifian", 24) # Object ke 2
print(p2.name)
print(p2.age)

"""## Fungsi __str__()"""

# Contoh: Representasi string objek TANPA __str__()
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

p1 = Person("John", 36)
print(p1)

# Contoh: Representasi string objek DENGAN __str__()
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def __str__(self):
        return f"Name = {self.name}, Age = {self.age}"

p1 = Person("John", 36)
print(p1)

"""## Metode Objek"""

# Contoh: Membuat metode di kelas
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def myfunc(self):
        print("Hello my name is " + self.name + " and I am " + str(self.age) + " years old")

p1 = Person("John", 36)
p1.myfunc()

p2 = Person("Arifian", 24)
p2.myfunc()

"""## Parameter self"""

# Contoh: Menggunakan nama parameter selain self
class Person:
    def __init__(mysillyobject, name, age):
        mysillyobject.name = name
        mysillyobject.age = age

    def myfunc(abc):
        print("Hello my name is " + abc.name)

p1 = Person("John", 36)
p1.myfunc()

"""## Mengubah Properti Objek"""

# Contoh: Mengubah properti objek
p1.age = 40
print(p1.age)

"""## Menghapus Properti Objek"""

# Contoh: Menghapus properti dari objek
del p1.age
# print(p1.age)  # Akan menghasilkan error karena properti telah dihapus

"""## Menghapus Objek"""

# Contoh: Menghapus objek
print(p1)
# print(p1)  # Akan menghasilkan error karena objek telah dihapus

"""## Pernyataan pass"""

# Contoh: Menggunakan pass untuk membuat kelas kosong
class Person:
    pass
