# -*- coding: utf-8 -*-
"""NumPy_Tutorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kKoYnpmyCO2wCHHRkyivYv3D0WvGiEjg

## NumPy

    NumPy adalah library Python yang digunakan untuk komputasi numerik.
    Install NumPy dengan perintah: `pip install numpy`.
"""

# Import NumPy
import numpy as np
print("NumPy Version:", np.__version__)

import numpy as np
# Membuat array sederhana
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

import numpy as np
# Membuat array 1D
arr1 = np.array([1, 2, 3])
print("1D Array:", arr1)

# Membuat array 2D
arr2 = np.array([[1, 2], [3, 4]])
print("2D Array:\n", arr2)

"""## NumPy Creating Arrays

    Anda bisa membuat array menggunakan berbagai metode.
    
"""

import numpy as np
# Array dari list Python
arr = np.array([10, 20, 30])

# Array dengan nilai nol
zeros = np.zeros((2, 3))

# Array dengan nilai acak
random_arr = np.random.rand(3, 3)

print("Array:", arr)
print("Zeros:\n", zeros)
print("Random Array:\n", random_arr)

"""## NumPy Array Indexing

    Mengakses elemen di array menggunakan indeks.
    
"""

import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print("Elemen pertama:", arr[0])
print("Elemen terakhir:", arr[-1])

"""## NumPy Array Slicing

    Mengambil sub-array dengan slicing.
    
"""

import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print("Elemen 1 hingga 3:", arr[0:3])
print("Elemen dari indeks 2 hingga akhir:", arr[2:])

"""## NumPy Data Types

    Memahami tipe data dalam NumPy.
    
"""

import numpy as np
arr = np.array([1, 2, 5])
print("Array:", arr)
print("Tipe Data:", arr.dtype)

"""## NumPy Copy vs View

    Perbedaan antara salinan data (copy) dan tampilan data (view).
    
"""

import numpy as np
arr = np.array([10, 20, 30])
copy_arr = arr.copy()
view_arr = arr.view()
copy_arr[0] = 99
view_arr[1] = 88
print("Original Array:", arr)
print("Copy Array:", copy_arr)
print("View Array:", view_arr)

"""## NumPy Array Shape

    Bentuk array mengindikasikan jumlah elemen di setiap dimensi.
    
"""

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", arr.shape)

"""## NumPy Array Reshape

    Mengubah bentuk array.
    
"""

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)
print("Reshaped Array:\n", reshaped)

"""## NumPy Array Iterating

    Melakukan iterasi pada elemen array.
    
"""

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
for x in arr:
    print(x)

"""## NumPy Array Join

    Menggabungkan dua array.
    
"""

import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
joined = np.concatenate((arr1, arr2))
print("Joined Array:", joined)

"""## NumPy Array Split

    Memisahkan array menjadi beberapa bagian.
    
"""

import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60])
split = np.array_split(arr, 3)
print("Split Arrays:", split)

"""## NumPy Array Search

    Mencari elemen dalam array.
    
"""

import numpy as np
arr = np.array([10, 20, 30, 40, 50])
result = np.where(arr == 30)
print("Index elemen 30:", result[0])

"""## NumPy Array Sort

    Mengurutkan elemen dalam array.
    
"""

import numpy as np
arr = np.array([30, 10, 50, 20, 40])
sorted_arr = np.sort(arr)
print("Sorted Array:", sorted_arr)

"""## NumPy Array Filter

    Memfilter elemen menggunakan kondisi.
    
"""

import numpy as np
arr = np.array([10, 20, 30, 40, 50])
filtered = arr[arr > 30]
print("Filtered Array:", filtered)